version: "2"
services:
  # PHP service
  app:
    build: ./docker/php/.
    container_name: kb-php
    working_dir: /var/www/site
    volumes:
      - ./site:/var/www/site
    networks:
      - kb-network
    depends_on:
      - mysql

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: kb-nginx
    working_dir: /var/www/site
    ports:
      - 8001:80
    volumes:
      - ./site:/var/www/site
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - kb-network
    depends_on:
      - app
      - mysql

  # Mysql service
  mysql:
    image: mysql:5.7.22
    container_name: kb-mysql
    #restart: always
    environment:
      - MYSQL_DATABASE=koalaBackend
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=kb
      - MYSQL_PASSWORD=kbpass
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      #- ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./data/db:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - kb-network

networks:
  kb-network:
    driver: bridge
